### ISSUE TITLE
Cannot import node module starts with '@'

### ISSUE THREAD

**Issue by zoigecyb** [joao-neves95/merger-js#218]
Hello.

my mergefile is

// $'bootstrap/dist/js/bootstrap.bundle.js'
// $'slick-carousel/slick/slick.js'
// $'@rjaros/bootstrap-select/js/bootstrap-select.js'

But i have an error  Error: ENOENT: no such file or directory, open 'D:\myproj\node_modules\rjaros\bootstrap-select\js\bootstrap-select.js'

physically all files exist. 
maybe for import node modules with '@' sign i have to use some different syntax?

**Comment by joao-neves95** [comment]
Hi,
You are using the correct syntax and this is definitely a bug on the syntax parser. For some reason, the `@` on the path is being removed. 

It's probably not a difficult fix, however, this is a very old software I did as my first ever pet project years ago, with a ton of tech debt, and to be honest I'm surprised it still works, given how fast node.js moves.

I'm sorry, but I don't have the time to maintain it anymore.

I'll archive the repo, as I forgot to.
